### ISSUE TITLE
API de cabina

### ISSUE THREAD

**Issue by ordomedina** [AgoraUS-G1-1617/Cabina-de-votaciones#12]
¿Podríais mostrar cómo se manda el formato de los votos para adaptar nuestra BD de almacenamiento?

**Comment by Guardsoul** [comment]
El método en cuestión que usamos es el siguiente:

`def vote_as_json(vote):
    to_dump_vote = {
        'id': vote.id,
        'id_poll': vote.id_poll,
        'age': vote.age,
        'genre': vote.genre,
        'autonomous_community': vote.autonomous_community,
        'answers': vote.answers
    }
    return json.dumps(to_dump_vote)`

Por lo tanto, retornamos un JSON con el siguiente formato:

`{
  "age": "24",
  "answers": [
       {
          "question":"Pregunta 1", 
          "answer_question":"SI"
       },
       {
          "question":"Pregunta 2",
          "answer_question":"SI"
       }        
  ], 
  "id": 1, 
  "autonomous_community": "Andalucia", 
  "genre": "Masculino", 
  "id_poll": 32778
} `

Un saludo.

**Comment by Guardsoul** [comment]
Cierro issue al no haber ninguna queja adicional al respecto.
