### ISSUE TITLE
Integración con subsistema de almacenamiento

### ISSUE THREAD

**Issue by josjimjim** [AgoraUS-G1-1617/Cabina-de-votaciones#13]
Es necesaria la integración con este subsistema para poder enviar y guardar los votos en la base de datos. Simplemente se sustituirá la URL a la que se manda la información, ya que el formato coincide con el de años anteriores.

**Comment by FerminFB** [comment]
El subsistema de almacenamiento ya esta en integracion continua, por favor cambiad las urls de vuestra aplicacion y comprobad que funciona todo correctamente, hemos adaptado el formato de los votos a los de vuestra api

**Comment by manugdf** [comment]
Cuando podáis dadnos un feedback sobre si os funciona o si por casualidad os da error.
Un saludo y sentimos la tardanza.

**Comment by jcliebanafdz** [comment]
Hemos realizado la integración con los compañeros de Recuento y Modificación, quienes asumieron también la creación de una API para almacenamiento. 
Dada la proximidad a la entrega, preferimos no cambiar dicha integración.

Un saludo.
