### ISSUE TITLE
Implementacion de seguridad

### ISSUE THREAD

**Issue by FerminFB** [AgoraUS-G1-1617/Cabina-de-votaciones#14]
Seria posible añadir en el JSON de un voto el nombre de usuario que vota y un token para que lo validara autenticacion? estos datos no se guardarían en la base de datos pero permitiría comprobar que el voto que se enviá es legitimo

**Comment by jcliebanafdz** [comment]
Sería una posibilidad a analizar, pero dada la proximidad a la entrega hemos dejado de añadir funcionalidades al sistema.
