### ISSUE TITLE
Página inicial devuelve error

### ISSUE THREAD

**Issue by Dionakra** [AgoraUS-G1-1617/Cabina-de-votaciones#8]
Buenas.

Al intentar acceder a la página principal de la aplicación en Integración continua (https://beta.cvotacion.agoraus1.egc.duckdns.org/) da un error del controlador al no existir la vista correspondiente.

Para resolverlo, podéis añadir en el fichero urls.py lo siguiente:

```
url(r'^$', 'app.views.cabinarecepcion'),
url(r'^index.html/$', 'app.views.cabinarecepcion'),  
```

Donde _cabinarecepcion_ es el método donde mostréis dicha vista, así no dará errores al iniciar.

Saludos.

**Comment by junlun** [comment]
El error se encuentra actualmente corregido y desplegado en estable. ahora puedes acceder al sistema sin especificar path (/)
Aún así las url antiguas (/cabinaus/cabinarecepcion) también funcionan.

**Comment by Dionakra** [comment]
Comprobado que está todo OK.

Pueden cerrar la Issue.

Saludos.
